import React, { useState, useEffect } from 'react'
import Navbar from '../components/Navbar'
import Head from 'next/head'
import Footer from '../components/Footer'

import { Flip, toast, ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'


export default function Contact() {
    const [userName, setUserName] = useState("");
    const [userEmail, setUserEmail] = useState("");
    const [userFeedback, setUserFeedback] = useState("");

    useEffect(() => {
        console.log("userName", userName);
        console.log("userEmail", userEmail);
        console.log("userName", userFeedback);

    },[userName, userEmail, userFeedback])


    const handleSubmit = async(e) => {
        e.preventDefault();
        const body = {userName, userEmail, userFeedback}
        try {
          const response = await fetch("/api/hello", {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify(body),
        });
        if (response.status !== 200){
          console.log("something went wrong");
          //set an error banner here
        } else {
          resetForm();
          console.log("form submitted successfully !!!")
          
          //set a success banner here
        }
        //check response, if success is false, dont take them to success page
        } catch (error) {
          console.log("there was an error submitting", error);
    
        }
      }
    
      const resetForm = () => {
        setUserName("");
        setUserEmail("");
        setUserFeedback("");

    }

    const notify = () => toast("Thanks for the feedback! Have a nice day ☺️");

    return (
        <div>

            <Head>
                <title>Contacts</title>
                <meta name="description" content="Generated by LunaCodr" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className='bg-black/95 w-full '>
                <div className='w-full bg-ts-img bg-cover bg-center bg-no-repeat bg-fixed '>
                    <div className='bg-black/80 w-full mx-auto '>
                        <Navbar />

                        <div>
                            <div className='w-full mx-auto'>
                                <div className='container mx-auto p-2 px-10'>
                                    <h1 id='contact-text' className='text-4xl xl:text-7xl font-semibold font-mont mt-40 text-pink'>Contact</h1>
                                    <div className='tracking-wider' id='talk-text'>
                                        <p className='text-white font-mont text-md mt-4 '>Let's talk about my website design or project.</p>
                                        <p className='text-white font-mont text-md'>Send me a message and we will be in touch within business oneday.</p>
                                    </div>

                                    <form className='' action='#' method="POST" onSubmit={(e) => handleSubmit(e)}>
                                        <div className='space-y-10 '>
                                            <div className=' mt-20 font-mont  antialiased ' >
                                                <input
                                                    onChange={(e) => setUserName(e.target.value)}
                                                    value={userName}
                                                    id='name-text'
                                                    name='name'
                                                    type='text'
                                                    placeholder='Your Name'
                                                    required
                                                    className='rounded-t-md outline-none py-3 px-2 font-semibold  border-pink border-b-2 bg-black/50 text-md w-full md:w-2/5 text-white  flex'
                                                />
                                            </div>
                                            <div>
                                                <input
                                                    onChange={(e) => setUserEmail(e.target.value)}
                                                    value={userEmail}
                                                    id='email-text'
                                                    name='email'
                                                    type='text'
                                                    placeholder='Email Address'
                                                    required
                                                    className='rounded-t-md outline-none py-3 px-2 font-semibold border-pink border-b-2 bg-black/50 text-md w-full md:w-2/5 text-white  flex'
                                                />
                                            </div>
                                            <div>
                                                <textarea
                                                    onChange={(e) => setUserFeedback(e.target.value)}
                                                    value={userFeedback}
                                                    id='area-text'
                                                    type='text'
                                                    name='message'
                                                    placeholder='Share your thoughts'
                                                    className='rounded-t-md outline-none py-3 px-2 font-semibold border-pink border-b-2 bg-black/50 text-md w-full md:w-2/5 text-white  flex'
                                                />
                                            </div>
                                        </div>
                                        <button type='submit' id='submit-button' onClick={notify}
                                            className='mt-10 bg-pink py-2 text-white w-full md:w-2/5 font-mont font-bold tracking-widest  rounded-xl hover:bg-white hover:text-pink duration-200 ease-in '>
                                            <span className=' text-sm' >Share Now</span>
                                        </button>
                                        <ToastContainer position="bottom-right" transition={Flip}
                                        
                                        />
                                    </form>
                                </div>
                            </div>
                            <div className='pb-40 container mx-auto '>

                            </div>
                        </div>
                    </div>
                </div>

                <Footer />
            </main>
        </div>
    )
}
