import Head from 'next/head'
import ExperiencedSection from '../components/ExperiencedSection'
import Footer from '../components/Footer'
import Header from '../components/Header'
import HeaderMobile from '../components/HeaderMobile'
import MusickSection from '../components/MusickSection'
import Navbar from '../components/Navbar'


export default function Home() {
  
  return (
    <div className=''>
      <Head>
        <title>Musick</title>
        <meta name="description" content="Generated by LunaCodr" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className='bg-black/95 w-full mx-auto'>
       <div className='w-full bg-metal bg-no-repeat  bg-cover bg-fixed'>
        <div className='bg-black/80  w-full mx-auto '>
          <Navbar/>
          <div className='hidden md:block'>
            <Header/>
          </div>
          <div className='block md:hidden'>
            <HeaderMobile/>
          </div>
          </div>
          </div>
          <div className='shadow-2xl'>
            <MusickSection/>
          </div>
          <div className='w-full bg-oneD bg-no-repeat  bg-cover bg-fixed'>
            <div className='w-full bg-black/80'>
            <ExperiencedSection/>
            </div>
          </div>

          <div>
            <Footer/>
          </div>
          
        
      </main>

     
    </div>
  )
}
